{% set version = "2.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-memoise
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/memoise_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/memoise/memoise_{{ version }}.tar.gz
  sha256: f85034ee98c8ca07fb3cd826142c1cd1e1e5747075a94c75a45783bbc4fe2deb

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cachem
    - r-rlang >=0.4.10
  run:
    - r-base
    - r-cachem
    - r-rlang >=0.4.10

test:
  commands:
    - $R -e "library('memoise')"           # [not win]
    - "\"%R%\" -e \"library('memoise')\""  # [win]

about:
  home: https://github.com/hadley/memoise
  license: MIT
  summary: Cache the results of a function so that when you call it again with the same arguments it returns the pre-computed value.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
