appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: FE+UMyALF0IztNz1Dn++uGBlI1ygHDkX3ZiGSNYhP+jt3Vxk3G4tK+9I3GW5+NgzCtMYxvf5NoPCMjNsZ+pvXi9aT8nj+ixrr5PKHcb8KF8a8vSMC2RxpYWIJ7a4RkSIgzwqp1Y9Ah4r/EvGk39o9RFBkc2Lb8Y5lrsS1qmw9H7yLdRVYnq9DjhbMSje1NjvYxulRGA8dWubElbdgKv3joRyEhTjMUPzpd3br80vbgUTww2JiWKU+0W8zymGbTyXoyoIjfUrw6X5zFY+4niTqHerY3PwDzRnqF/RBWIBS0tDjZrom4ImmmSP2g5zauxbld7DfnYe986lLgTkb2hegSt0+yODDPTqOXqZroPiKIDy8AhrjHOIn+jP8hEKd1nUMcdUs7r2uehi5Zktm9no+3him+Jh+8Q0GUT3WACiPAEyOV0t5R5MvQNfTTfq5A7IOkMheYZ33m+xRbFxEQ9wzP1vcNdScYymK7/m3lYS7DsTLAX2s65v77UNvUybTxEufptNZ5btwZqQRK3JFlfRNzTCsCfRAmAFWDMVD/wK0QTv8MEY+vf3QFEEMacNtWjKc0QQ4m9YDt7OHcDOPrO97I3QzqFd6y83GxI2KbF/Ozdm+AH1detVhrj5lnaTcw6RyLazXytsu5ShLh2sr8nh6QICGCfZkY166DDHiCHarig=}
